### ISSUE TITLE
Centralized method to retrieve current Medicare pricing by CPT

### ISSUE THREAD

**Issue by dportnoy** [demand-driven-open-data/ddod-intake#1]
Problem: Currently, you have to go to multiple sites and download inconsistent excel or CSV files to capture this data.

Solution: Centralized dataset or API that includes Medicare pricing for each CPT and locale

Value: This solution provides price transparency for consumers and enables companies to provide cost transparency tools.  CMS often sets the pricing standards for private insurers as well.

**Comment by dportnoy** [comment]
Created page for full use case specifications and solution: http://hhs.ddod.us/wiki/Use_Case_1

**Comment by ftrotter** [comment]
The problem with a system like this is the many factors that go into calculating a given CPT code. Like location (i.e. state/Zip etc) and whether it is hospital or provider based. Other kickers... 

It might be possible to solve this using the X12 EDI standards.. I vaugely recall some kind of "query for price" functionality defined in one of the lesser used standards... Then you put a RESTful/OAuth API on top of it... magic.

-FT

**Comment by dportnoy** [comment]
Closing. Moved to "Leads" section (demand-driven-open-data/DDOD-Leads#10) until this request could be defined as a use case.
