### ISSUE TITLE
CDC - Outbreaks reported by week

### ISSUE THREAD

**Issue by dportnoy** [demand-driven-open-data/ddod-intake#10]

**Comment by cornstein** [comment]
Each week, CDC posts information on communicable diseases in the MMWR (an example: http://www.cdc.gov/mmwr/pdf/wk/mm6410md.pdf). The data is also available on data.gov (example: https://data.cdc.gov/NNDSS/NNDSS-Table-II-Mumps-to-Rabies-animal/d69q-iyrb). But the data is not historical, except for a couple recent years. It would be good to create a historical archive for each disease, perhaps as a separate table, updated weekly? monthly?

**Comment by dportnoy** [comment]
Created page for full use case specifications and solution: http://hhs.ddod.us/wiki/Use_Case_10

**Comment by betshsu** [comment]
@cornstein Is this data still of interest?  If so, could you articulate the value and use of the data so that it can be structured as a use case?  How far back would you like the data to go?  Thanks.

**Comment by dportnoy** [comment]
@cornstein this use case potentially has a lot of merit.  Looks like you're right about not having much history.  Only 2014 and 2015 are available for query online via https://data.cdc.gov:
- https://data.cdc.gov/browse?category=NNDSS&tags=2014: 13 items
- https://data.cdc.gov/browse?category=NNDSS&tags=2015: 17 items

Compared to the above the MMWR PDFs have different level of detail:
- Table I (Infrequently reported notifiable diseases):
  - Shows total cases for each of last 5 years for 61 diseases.
  - Missing breakout by week of the year, which https://data.cdc.gov has
- Table II (Provisional cases of selected notifiable diseases) has about 30 diseases listed
  - It's not immediately clear how these 30 diseases line up with 12 (for 2014) or 16 (for 2015) tables at https://data.cdc.gov
  - Missing breakout by week of the year, which https://data.cdc.gov has

The oldest history I see is aggregated to by year back to 2009 (https://data.cdc.gov/NNDSS/NNDSS-Table-I-infrequently-reported-notifiable-dis/wcwi-x3uk), but only for infrequently reported diseases

---

That said, we haven't heard back from you in 7 months and will need to close the use case if we don't get more input on, specifically:
- How you plan to use the data.  What's the value of this data to your organization and the public at large.
- Specifications: List fields needed, how far back should "history" go, what lag time is acceptable, do  certain fields need to match predefined values for joining with other datasets, data format (CSV, JSON, Excel)

Could you respond by Fri 10/23. Thanks!

**Comment by betshsu** [comment]
While CDC only provides MMWR historical information back through 2014, Project Tycho out of the University of Pittsburgh provides machine readable historical information back through 1888.  See wiki for full specifications http://teal.ddod.us/wiki/Use_Case_10:_Historical_archive_of_disease_outbreaks
