### ISSUE TITLE
Need de-ident claims for utilization & quality analytics

### ISSUE THREAD

**Issue by dportnoy** [demand-driven-open-data/ddod-intake#15]
USE CASE
**Description:** Need a claims dataset at patient level in order to perform utilization analytics and assess physician quality.  Examples of quality might include readmissions and misdiagnosis.  

**Value:** 
- Steer patients toward better quality physicians.  Reward good physicians with better reputation and more patients.  This would be a good complement to the cost utilization data released by CMS in 2014.
- Our network reaches over 50mm+ patients per month, and we’d love to share cost and quality data with them. We haven’t used the utilization dataset yet, however, because of the need for “quality” related info before sharing. 
- This would obviously be pertinent to provider groups, payers, self insured employers, and social workers who help underserved populations choose care.

**Challenge:** Patient level claims aren't currently available for such analysis

**Customer:** Provides quality metrics and reporting on providers to consumers.

**Specifications:**
- each claim, de-identified but still individual-trackable

**Comment by dportnoy** [comment]
Created page for full use case specifications and solution: http://hhs.ddod.us/wiki/Use_Case_15

**Comment by ftrotter** [comment]
This is what the Data Encleave program is for and it is being opened up to industry in  Sept 2015. 
http://www.cms.gov/Newsroom/MediaReleaseDatabase/Press-releases/2015-Press-releases-items/2015-06-02.html

We should celebrate the awesomeness of Niall Brennan and team and close this ticket.

-FT

**Comment by dportnoy** [comment]
@ftrotter Do you know anyone who has already started getting this new data?  Any challenges so far?

**Comment by dportnoy** [comment]
Also, might look outside of de-ident claims for provider quality.  Examples are DDOD use cases:
- https://github.com/demand-driven-open-data/ddod-intake/issues/3
- https://github.com/demand-driven-open-data/ddod-intake/issues/4
- https://github.com/demand-driven-open-data/ddod-intake/issues/27
- https://github.com/demand-driven-open-data/ddod-intake/issues/35

**Comment by dportnoy** [comment]
Update...  Asking originator to respond to comments and further refine specifications.

**Comment by dportnoy** [comment]
Closing use case, since it's not specific enough to be actionable and other use cases already deal with provider quality.  Some are based on de-identified or aggregated claims: #38, #39.  Others on MU, PQRS, and VBM metrics: #3, #4, #35.  Also CAHPS consumer surveys #27 and HRSA health center performance #23.  Will reopen if @doctor.com has other specifications.
