### ISSUE TITLE
Leakage reduction

### ISSUE THREAD

**Issue by dportnoy** [demand-driven-open-data/ddod-intake#19]
Specifications: ~~https://github.com/demand-driven-open-data/ddod-intake/wiki/Use-Case-19~~

(Moved to http://hhs.ddod.us/wiki/Use_Case_19)

**Comment by ftrotter** [comment]
This title should be clarified. It is specifically talking about ACOs.

Generally, getting this data open is what made me famousish. https://questions.cms.gov/faq.php?faqId=7977

Also the ACO members are required to release thier providers on their websites. 

In short the data required to this analysis is already open. This should be briefly celebrated then closed. 

If we want to have something requested, lets request specific NPI ACO membership publishing from CMS in time with the monthly CCLF file release... now that would be a substantial improvement. 

This is too large and general and should be closed in favor of more specific tickets...

-FT

**Comment by dportnoy** [comment]
Update...  Checking again with originator to fully define the use case specs.

**Comment by dportnoy** [comment]
Update...  Held discussion with @ fibroblast, one of request originators.  They said they'll provide additional specifications after internal discussion and review of available data sources.

**Comment by dportnoy** [comment]
## Potential data problem:

DocGraph had a recent data retraction associated with the Teaming dataset mentioned at http://radar.oreilly.com/2012/11/docgraph-open-social-doctor-data.html and https://questions.cms.gov/faq.php?faqId=7977.  

Details and possible fix is posted here: http://www.docgraph.org/notice-teaming-data/.

**Comment by dportnoy** [comment]
@fibroblast, could you provide input into your needs by Fri 10/23.

**Comment by dportnoy** [comment]
@fibroblast, closing for now, since needed input not yet provided.  Can reopen if that changes.
