### ISSUE TITLE
Need one step process to access physician

### ISSUE THREAD

**Issue by dportnoy** [demand-driven-open-data/ddod-intake#2]
Use case specifications: ~~https://github.com/demand-driven-open-data/ddod-intake/wiki/Use-Case-2~~
http://hhs.ddod.us/wiki/Use_Case_2

**Comment by ftrotter** [comment]
This should be modified. The title should be "provide automated feedback to NPPES data". As it stands it sounds like its asking for something new, which it isnt. Its just asking for what is already there to be right.

**Comment by dportnoy** [comment]
Closing. As it stands, this item has elements of provider directory interoperability efforts (http://hhs.ddod.us/wiki/Interoperability:_Provider_network_directories), the NPPES on FHIR concept (http://david.portnoy.us/provider-network-directories-on-fhir/) and IDEA Lab's NPPES modernization project (http://www.hhs.gov/idealab/projects-item/modernizing-the-national-plan-and-provider-enumeration-system/).  But it needs a concrete user and specifications to be a use case.
