### ISSUE TITLE
More granularity on patient satisfaction scores (CAHPS Hospital Survey)

### ISSUE THREAD

**Issue by dportnoy** [demand-driven-open-data/ddod-intake#27]
Per conversation with Richard Ferrans, MD 4/28/2015 on Patient Satisfaction scores released by CMS, which were collected by Press Ganey
- See [Hospital Compare Star Ratings Fact Sheet from 2015-04-16](http://www.cms.gov/Newsroom/MediaReleaseDatabase/Fact-sheets/2015-Fact-sheets-items/2015-04-16.html)

---
### [Survey of patients' experiences (HCAHPS)](http://www.medicare.gov/hospitalcompare/Data/Overview.html)

The Centers for Medicare & Medicaid Services (CMS), along with the Agency for Healthcare Research and Quality (AHRQ), developed the HCAHPS (Hospital Consumer Assessment of Healthcare Providers and Systems) Survey, also known as Hospital CAHPS®, to provide a standardized survey instrument and data collection methodology for measuring patients' perspectives on hospital care. The HCAHPS Survey is administered to a random sample of patients continuously throughout the year. CMS cleans, adjusts and analyzes the data, then publicly reports the results. The HCAHPS survey- Opens in a new windowExit Disclaimer - Opens in a new window is 32 questions in length—21 substantive items that encompass critical aspects of the hospital experience, four screening questions to skip patients to appropriate questions, and 7 demographic items that are used for adjusting the mix of patients across hospitals for analytical purposes. Hospital Compare currently reports results for 7 composite topics, 2 individual topics and 2 global topics, as follows:

Composite topics

Nurse communication (questions 1, 2, 3)
Doctor communication (questions 5, 6, 7)
Responsiveness of hospital staff (questions 4, 11)
Pain management (questions 13, 14)
Communication about medicines (questions 16, 17)
Discharge information (questions 19, 20)
Care transition (questions 23, 24, 25)
Individual topics

Cleanliness of hospital environment (question 8)
Quietness of hospital environment (question 9)
Global topics

Overall rating of hospital (question 21)
Willingness to recommend hospital (question 22)
Hospital-level results are publicly reported on the Hospital Compare website four times a year. HCAHPS results are based on four quarters of data on a rolling basis.

**Comment by dportnoy** [comment]
Created page for full use case specifications and solution: http://hhs.ddod.us/wiki/Use_Case_27

**Comment by ftrotter** [comment]
This is an important request. I think it should be clarified specifically what is not being released. 

We will FOIA this one if nothing happens on it here...

-FT

**Comment by marks** [comment]
What data is being asked for here that is not available at the site that powers the Hospital Compare interface (https://data.medicare.gov/Hospital-Compare/Patient-survey-HCAHPS-Hospital/dgck-syfz)?

**Comment by marks** [comment]
@ftrotter question for you, above, when you get a chance

**Comment by dportnoy** [comment]
Update...  Checking again with originator to fully define the use case specs.

**Comment by dportnoy** [comment]
Per conversation with originator, here are additional requirements:
1. Need a lower level of granularity: Broken by hospital department, rather than hospital level.
2. It's useful to have the number of samples requested, not just # of responses
3. We need to be able to look at number of responses as a fraction of number of acute care discharges (can be obtained elsewhere) to identify validity / trust

@ftrotter Thoughts on above?

**Comment by betshsu** [comment]
This information is not currently a priority for the requester, so use case being closed pending further interest and specifications from the requester.
