### ISSUE TITLE
Connect Physician ID in Open Payments to NPI

### ISSUE THREAD

**Issue by dportnoy** [demand-driven-open-data/ddod-intake#29]
As noted by Waldo Jaquith 4/27/2015
- Open Payments records uses: Physician IDs and Physician Profile IDs  (sequential integers)
- NPPES and some other datasets use NPI
- **Need:** User needs to connect Open Payments records to datasets containing NPI

**Comment by dportnoy** [comment]
~~Created use case entry: https://github.com/demand-driven-open-data/ddod-intake/wiki/Use-Case-29~~ Moved

**Comment by dportnoy** [comment]
Crated page for full use case specifications and solution: http://hhs.ddod.us/wiki/Use_Case_29

**Comment by dportnoy** [comment]
Discussion with CMS/CPI on potential statutory reasons for missing NPI.

**Comment by marks** [comment]
+1 - would love to see NPI added to OpenPayments data.

**Comment by dportnoy** [comment]
@marks Added.  Tks!

**Comment by ftrotter** [comment]
This ticket should be closed. The ACA specifically forbids this linking. Drug companies et al are required by law to report to HHS using the NPI. (Which is you read their report here: http://www.cms.gov/OpenPayments/Downloads/Open-Payments-April-2015-Report-to-Congress.pdf was something of a problem for the whole process)

But they are forbidden from releasing that data. To find the law, go to this document http://www.gpo.gov/fdsys/pkg/PLAW-111publ148/pdf/PLAW-111publ148.pdf  and search for the phrase:

(viii) does not contain the National Provider Identifier of the covered recipient, and

We (DocGraph) are considering doing this mapping and releasing it as an open data set, and we can discuss other ways (i.e. DocSpot considering doing this too http://www.medstartr.com/projects/471-connecting-healthcare-data-linking-open-payments-to-npi)... 

Anyone who solves this problem in an open way should leave a comment here, but this should be closed. Its a success too! sometimes the answer will be no, but getting to a firm answer is a positive result and should be celebrated!

-FT

**Comment by dportnoy** [comment]
I pinged @DocSpotHealth via twitter to see if they want to weigh in.

**Comment by dportnoy** [comment]
Lots of updates made to http://hhs.ddod.us/wiki/Use_Case_29:_Link_Open_Payments_dataset_to_NPI, including acknowledgement to @ftrotter 

@waldoj, please weigh in

**Comment by dportnoy** [comment]
@ftrotter, @marks, @waldoj,  What do you think have been examples of the highest value uses of Open Payments as it stands?  I want to be sure I'm not being overly critical and pointing out the value as well.

**Comment by waldoj** [comment]
David, I think your summary of the state of things is spot-on, and the legislative explanation is really helpful. I appreciate that HHS cannot do something that is explicitly prohibited by law—there's no getting around that. And both of your proposed solutions (match records or get data from somebody who has matched records) are certainly sensible. I'm afraid my domain expertise is far too weak to know what the highest value uses are of Open Payments—I'll have to defer to @ftrotter and @marks on that one.

Thanks for following up on this!

**Comment by vaibkv** [comment]
I can do this linking if it's not illegal to do it.

**Comment by dportnoy** [comment]
@vaibkv  Thanks for your note.  The legislation explicitly forbids this linking by CMS/HHS.  That said, there have been some organizations that have done this on their own for various purposes.  But without objective analysis, it's hard to identify the degree of accuracy they were able to achieve.  Regardless, any resulting data unfortunately cannot be posted here.

**Comment by vaibkv** [comment]
Got it...thanks!

**Comment by thmadmin** [comment]
If legislation forbids reporitng NPI then why NPI is listed on OIG exclusion?

**Comment by tbirur** [comment]
If legislation forbids displaying NPI then why in OIG exclusion they list NPI ??

**Comment by Breza** [comment]
Does anyone know the status of NPI-Open Payments matching? CMS has said they will start publishing the crosswalk, but I haven't been able to find anything yet.
