### ISSUE TITLE
Need for greater granularity in PQRS published benchmarks

### ISSUE THREAD

**Issue by DavidXPortnoy** [demand-driven-open-data/ddod-intake#3]
Need for greater granularity in PQRS published benchmarks.  The benchmarks are currently derived from the aggregation of quality data submitted through multiple data collection methods, but it would be helpful if in addition the data from each collection method were used to calculate separate benchmarks for that collection method (e.g. set of benchmarks for data collected through GPRO registry, set of benchmarks for data collected through individual EP registry, etc.).  The value of this is to enable additional insights into the relative data quality and measure performance of different data collection methods, thereby improving our understanding of how to more accurately and effectively measure care delivery and patient safety risks.

Additionally, need to get information about physicians and groups who failed to attain MU or report PQRS in a given year. 

Customer: Assists providers with meaningful use attestation and workflow optimization

**Comment by dportnoy** [comment]
Created page for full use case specifications and solution: http://hhs.ddod.us/wiki/Use_Case_3

**Comment by dportnoy** [comment]
Updates to solution details made from notes: http://hhs.ddod.us/wiki/Use_Case_3
