### ISSUE TITLE
Physician Based Modifier Results On Provider Level

### ISSUE THREAD

**Issue by Jordanrau** [demand-driven-open-data/ddod-intake#35]
CMS evaluates physician groups -- and soon individual physicians -- on cost and quality and adjusts the pay upward, downward or not all all based on the results. CMS has released the aggregate results for more than 1,000 physician groups: http://www.cms.gov/Medicare/Medicare-Fee-for-Service-Payment/PhysicianFeedbackProgram/Downloads/2015-Value-Modifier-Results.pdf 

CMS should releasd how each provider scored on cost and quality and what their payment adjustment is -- just as CMS releases this for hospitals in the Hospital Value-Based Payment Program. CMS should release parallel data for each physician group/physician, showing which PQRS measures were used in their scoring, how they scored, what cost and quality scores CMS calculated for them and what payment adjustment occurred. CMS already provides this information to each provider on the QRURs.

**Comment by cornstein** [comment]
This makes a lot of sense. It should be released.

**Comment by dportnoy** [comment]
@Jordanrau @cornstein Thank you for your entry.  Will process shortly.

**Comment by ftrotter** [comment]
Uhmm plus one... Of course if @cornstein  likes it you can probably guess that I will too...

**Comment by betshsu** [comment]
@Jordanrau @cornstein @ftrotter Have you see the updates that have been made to the wiki of related use case #4 (http://hhs.ddod.us/wiki/Use_Case_4)?

**Comment by dportnoy** [comment]
Tweeting @Jordanrau for input on prior question about relation to use case #4.

**Comment by Jordanrau** [comment]
Hi David,

Sorry for the delay in responding. I’m not sure what your question is. In response to the comments on the wiki:

(1)  Regarding confidentiality: I’m not a FOIA expert, but I am pretty sure that payments by Medicare are public regardless of CMS pledge to keep the data confidential. The Part B/Wall Street Journal case should have resolved that issue.

(2)  Value: The MIPS is major change to physician payment and an enormous amount can be learned about how to do that correctly and fairly from the PVBM. From a public perspective, identifying the groups by name will help independent examinations – by journalists, researchers, etc. – examine how effectively this first effort at value-based payment is working for physician groups and that can inform the crafting of the MIPS.

Let me know if there are other questions you’d like me to address.

Best,

Jordan

Jordan Rau | Senior Correspondent | Kaiser Health News | 202.654.1362 | @jordanrau | jrau@kff.orgmailto:jrau@kff.org

**Comment by dportnoy** [comment]
@Jordanrau Thank you for the feedback!  We'll do some more digging and post an update.

**Comment by dportnoy** [comment]
@Jordanrau, @cornstein, @ftrotter, based on the sunsetting and sensitivity reasons provided by the data owners for Use Case #4 against funding efforts to make VBM detail available, I think your best route may be to start with a FOIA request.  FOIA requests have a lot of weight behind them and could overcome these hesitations, even if some of them are coming from the general counsel.  The biggest challenge is dealing with the significant current backlog.  

Based on a publicly requestable listing of FOIA requests, I can't find any prior requests for Value-Based Payment Modifier (VM), PQRS detail or global view of QRURs (Quality and Resource Use Reports).  So we can't leverage what somebody already started.  But if you make the needed FOIA requests and notify me with the specifics, I could then reach out again to the data owners to see if I could lend a hand such that you're not as impacted by the FOIA backlog and even assist in getting the data into a format conducive for analysis.  You might want to make two requests: 
1. Using specifications similar to http://hhs.ddod.us/wiki/Use_Case_4#Specifications.
   - Specify the target organization for the request:  CMS --> Center for Medicare --> Performance-Based Payment Policy Group --> Division of Value-Based Payment  
2. Consider creating a separate FOIA request for NPI-to-organization mapping used during creation of PQRS metrics.  (Similar to #20.  I believe TIN cannot be disclosed, but you could request a unique organization name plus HQ address.)

**Comment by Jordanrau** [comment]
Ok thanks for getting back to me.

Jordan

Jordan Rau | Senior Correspondent | Kaiser Health News | 202.654.1362 | @jordanrau | jrau@kff.orgmailto:jrau@kff.org

**Comment by dportnoy** [comment]
@Jordanrau  please let me know if you choose the FOIA route.  Thanks!
