### ISSUE TITLE
Data Catalogs as Spreadsheets and Participate in Meetups for Feedback on Data Science on HHS Data Sets

### ISSUE THREAD

**Issue by brandniemann** [demand-driven-open-data/ddod-intake#36]
Chris, David, and Damon, Thank you for an excellent DataLab session at HDP 2015.

My suggestions are:

Provide Health.data.gov and cms.data.gov data catalogs in spreadsheet format with web links to metadata, data, and data dictionaries; and

Participate in our Federal Big Data Working Group Meetups to provide feedback to agencies and OMB on data science results (e.g. our USDA Data Science MOOC is our more recent best practice example):http://www.meetup.com/Federal-Big-Data-Working-Group/events/221457264/.­ Best regards, Brand

**Comment by dportnoy** [comment]
@brandniemann Thank you for your entry.  Will process shortly.

**Comment by marks** [comment]
@brandniemann - some of what you are looking for should be in the Project Open Data files for data.cms.gov (at http://data.cms.gov/data.json) and healthdata.gov (https://healthdata.gov/data.json). 

You might also want to check out the Project Open Data project at https://project-open-data.cio.gov/v1.1/schema/ to advocate for more metadata fields such as data dictionaries, etc. to be included in the standard

**Comment by dportnoy** [comment]
@brandniemann, thank you for your suggestion.

+1 on @marks comment noting that there's a well defined DCAT-complaint schema described at https://project-open-data.cio.gov/v1.1/schema/.  It's used throughout all of federal government and harvested up to http://data.gov.  

However, there hasn't been wide adoption of indexing of the field-level data dictionary.  If there are sufficient resources, we would like to eventually add this capability to HealthData.gov.  Doing so would also provide for a more powerful discovery at the field level and enable a feature that assists in linking across datasets.  Adding semantic tagging to field definitions would make it even more powerful.  I've written a couple posts on this topic:
- http://david.portnoy.us/field-level-data-dictionaries-for-open-data/
- http://david.portnoy.us/using-ddod-to-identify-and-index-data-assets/
- http://david.portnoy.us/what-happened-to-the-semantic-web/
- http://david.portnoy.us/linked-data-and-semantic-web/

---

That said, your entry is categorized as a general suggestion.  It must me noted that to be a workable use case, a request must be achievable, measurable, and specific, with a well defined value proposition.  So working within the context of a DDOD use case, we need to close this item.  Thank you for your involvement and being such an active participant in the user community.  Your suggestions are always welcome.

**Comment by brandniemann** [comment]
David, Thank you. I have found a way to do this semantic linking and index searching in Spotfire and will show that for the DataAct Data sets at our November 16th meetup:

http://www.meetup.com/Federal-Big-Data-Working-Group/events/225137696/

Best regards, Brand
