### ISSUE TITLE
FFM Network Adequacy data to meet directory requirements

### ISSUE THREAD

**Issue by dportnoy** [demand-driven-open-data/ddod-intake#37]
Description: CMS/CCIIO should already have QHP provider network data that it collects annually through the QHP certification process.  The fields in this data should be adequate to meet another requirement for machine-readable files.  We need to see if the fields provided are sufficient and the process can be automated.  If so, we would just need to provide this data on a monthly basis.

Customer: The Provider Directory Workgroup (PDWG) formed to address CMS's requirement to maintain machine-readable provider network directories.

Related discussion: http://hhs.ddod.us/wiki/Implementation:_Provider_network_directories

**Comment by dportnoy** [comment]
Specifications are located here: http://hhs.ddod.us/wiki/Use_Case_37

**Comment by ftrotter** [comment]
This is important data. I care about this. It should also be noted that Medicare/Medicaid Advantage plans also have to demonstrate network adequacy. Is this something that can be merged? Should it be its own ticket?

**Comment by dportnoy** [comment]
@ftrotter Thanks for submitting FOIA request for QHP network adequacy files.  Yes, I think it would make sense to have a separate request for Medicare/Medicaid Advantage plans, since it would most likely be fulfilled by different people.

**Comment by dportnoy** [comment]
Added network-level PUF data source (http://hhs.ddod.us/wiki/Use_Case_37)  to use case writeup.

**Comment by dportnoy** [comment]
@ftrotter  What did you hear back from FOIA on your request?  We may be able to work this one as FOIA / DDOD "parallel" request.

**Comment by dportnoy** [comment]
Closing use case.   The relevant data needed to recreate the entire network for a QHP can now be found in the "Machine-readable URL PUF" (aka, MR-PUF).   The solution has been posted here: http://hhs.ddod.us/wiki/Use_Case_37#Solution
