### ISSUE TITLE
Make VBM (Value-Based Payment Modifier) reporting for all groups publicly available

### ISSUE THREAD

**Issue by DavidXPortnoy** [demand-driven-open-data/ddod-intake#4]
On Value-Based Payment Modifier (VBM) reporting, provide the quality composite and cost composite scores by group (as identified by name and headquarters location and 1:1 with tax ID) for each performance year. Currently, these scores are only available within each group's private QRUR report. This additional transparency would be a win for consumers.

Customer: Assists providers with meaningful use attestation and workflow optimization

Specifications: ~~https://github.com/demand-driven-open-data/ddod-intake/wiki/Use-Case-4~~
http://hhs.ddod.us/wiki/Use_Case_4

**Comment by Jordanrau** [comment]
Great idea!

**Comment by dportnoy** [comment]
Updates made to http://hhs.ddod.us/wiki/Use_Case_4 from notes.
