### ISSUE TITLE
Core Data Set: Patient demographics for provider utilization datasets

### ISSUE THREAD

**Issue by ftrotter** [demand-driven-open-data/ddod-intake#40]
Medicare patients do not all look alike. People with disabilities, who are under the age of 65, can be covered under Medicare. A provider who sees a majority of patients in this category should have their other data points interpreted completely differently. 

Similarly, a doctor whose average patient age is 95 should be evaluated differently then one whose patient age is 67. 

Tranches of ages and gender (which is not just two values btw) should be considered for this report... again there is no reason to risk re-identification for these general cases.. .so no patient counts under 50 would be just fine...

-FT

**Comment by ftrotter** [comment]
Thoughts @cornstein? Can you endorse?

**Comment by dportnoy** [comment]
@ftrotter, could you specify all of the fields needed in this dataset.

**Comment by cornstein** [comment]
Hi @DavidXPortnoy @ftrotter. CMS is currently processing this request as a FOIA, so I think we'll just handle it that way. Thanks!

**Comment by dportnoy** [comment]
@cornstein, do you have any params on the FOIA request -- text of request, date requested, estimated delivery, etc.?  Also, we're experimenting with processing DDOD in parallel with FOIA to use the work done for a request as an opportunity to create ongoing data refreshes.

**Comment by dportnoy** [comment]
Specifications documented here: http://hhs.ddod.us/wiki/Use_Case_40

**Comment by dportnoy** [comment]
An update has been made on 10/5/2015 to the relevant tables of CY 2012 and CY 2013 "Medicare Provider Utilization and Payment Data: Physician and Other Supplier" datasets that includes the items asked for.  Provider-level summary tables now include aggregated information on the following beneficiary attributes:
1. Age
2. Sex
3. Race
4. Medicare and Medicaid entitlement
5. 16 chronic conditions
6. Risk scores

See http://hhs.ddod.us/wiki/Use_Case_40#Solution for full description.
