### ISSUE TITLE
Medicaid MCO data

### ISSUE THREAD

**Issue by declan** [demand-driven-open-data/ddod-intake#46]
I'm looking for information on Medicaid Managed Care Organizations. Each state's info is published separately in one of [these 50 PDFs](http://www.medicaid.gov/medicaid-chip-program-information/by-topics/delivery-systems/managed-care/managed-care-profiles.html), but it would be nice if the data were aggregated somewhere.

It looks like the Data and Systems Group published a report on this [back in 2012](http://www.medicaid.gov/medicaid-chip-program-information/by-topics/data-and-systems/medicaid-managed-care/medicaid-managed-care-enrollment-report.html), but I can't find anything more recent.

**Comment by betshsu** [comment]
Thanks @declan.  To structure this request as a Use Case (such as http://hhs.ddod.us/wiki/Use_Cases), can you describe how this data will be used and the value it delivers?

**Comment by betshsu** [comment]
@declan We have a call with the folks that produce the Medicaid Managed Care Enrollment Report next week to get more info.  Can you clarify exactly which data fields are of interest (or all?)?

**Comment by betshsu** [comment]
Entry for specifications created: http://hhs.ddod.us/wiki/Use_Case_46

@declan, feel free to edit.  Just sign in with any Google account

**Comment by declan** [comment]
Hi @betshsu I do intend to fill this out, will get to it by Friday at the latest.

**Comment by betshsu** [comment]
Thanks @declan.  Would be great to have the info before Monday so we can be as informed as possible going into the call.

**Comment by dportnoy** [comment]
@declan We had a call with the Data and Systems Group (DSG).  Some more recent and consolidated data can be made available imminently and there are future data reporting changes coming up that could affect your workflow.  We're in the process of identifying what information can be publicly released and should have an update shortly.

**Comment by betshsu** [comment]
We have confirmation that the 2013 and 2014 data will be released in both Excel and pdf format.  There are a number of Excel files, some with more information than in the pdf.  

The 2013 data is now up here: http://www.medicaid.gov/medicaid-chip-program-information/by-topics/data-and-systems/medicaid-managed-care/medicaid-managed-care-enrollment-report.html 

Here is my quick summary of the content of the (mostly) Excel files in the download:
- 1_Enrollment by program type (all) -- single row per state; columns of total all eligibles Medicaid enrollment and breakdown of enrollment by plan type (MCO, PCCM, MLTSS, etc)
- 3_Comprehensive MCO penetration -- single row per state; column of total Medicaid enrollees and breakdown by all medicaid managed care and comprehensive managed care
- 4_Enrollment by program and plan -- multiple rows per state; columns of program name (type), plan, geographic region, total Medicaid only enrollment, dual enrollment, total enrollment
- 5_MLTSS enrollment -- single row per state; columns of total managed care enrollees and broken down by comprehensive managee care, managed LTSS, and other MLTSS
- 6_features by enrollment population -- single row per "feature" (population type); columns of number of managed care programs by type and mandatory/voluntary
- 7_Features by QA and performance incentive -- single row per "feature" (either QA or performance metric); columns of total number of programs by program type
- 2013 MMCDCS state tables -- one tab per state; seems to contain the data in the state profile pdfs
- zip file of individual state table pdfs

The 2014 data is in process and won't be released until the end of the year.

@declan does this fulfill your needs or are there other deficiencies in the data?

**Comment by declan** [comment]
@betshsu I believe this covers it, reviewing tonight. Thank you very much for helping to make this public.

**Comment by betshsu** [comment]
@declan Great, let us know if there is anything missing that you need.

**Comment by betshsu** [comment]
Updated wiki with info regarding update frequency and content of Excel files.
