### ISSUE TITLE
Consolidated registry of marketed medical devices

### ISSUE THREAD

**Issue by dportnoy** [demand-driven-open-data/ddod-intake#5]
Specifications: ~~https://github.com/demand-driven-open-data/ddod-intake/wiki/Use-Case-5~~
http://hhs.ddod.us/wiki/Use_Case_5

**Comment by dportnoy** [comment]
@procured, please provide feedback to [solution 5](https://github.com/demand-driven-open-data/ddod-intake/wiki/Solution-5).  
- Any clarifications needed?
- Issues, concerns?
- Desire to participate in feedback and validation of long term solution?

**Comment by dportnoy** [comment]
Created entry to this use case on HealthData.gov

**Comment by wdanford** [comment]
This also precisely summarizes our issues. Thanks!  Would definitely like to participate in a long term solution.

**Comment by dportnoy** [comment]
@wdanford you should watch subscribe to notifications for this issue 
1. For the short term R&L [workaround using FOIA](https://github.com/demand-driven-open-data/ddod-intake/wiki/Solution-5#foia-short-term), let me know if the instructions get you the result faster.  We could also try specifying actual query code and SME in the request for improved consistency.
2. I'm checking with Data Owner about next steps on participation in long term solution

.

**Comment by dportnoy** [comment]
Ann Ferriter (FDA/CDRH/DAPO) was out for a week and will talk to Dave Gartner (FDA/CDRH/DAPO/RRB) next week about questions:
1. For the short term R&L workaround using FOIA, whether it's possible to obtain the actual source code of the query that has been run for prior requests.
2.  On the long term solution described ("Publicly accessible website to access recall records published directly from RES and an API is in the works"), which of the following would be possible:
   ·  a)  Make it possible for Data Users to participate in pre-release validation
   ·  b)  Provide information about future data model and other specifications  (This can be documented in the wiki)
   ·  c)  Keep Data User (and everyone else) updated on release schedules or delivery status change by simply making a comment on the Github issue #5

**Comment by dportnoy** [comment]
Confirmed deployment via OpenFDA scheduled for release this summer.

**Comment by dportnoy** [comment]
Update: OpenFDA has made new device data available
- Announcement: https://open.fda.gov/update/openfda-unveils-cache-of-medical-device-data/
- Location of added data on OpenFDA  (https://open.fda.gov/device/event/)
  - Device classification: https://open.fda.gov/device/classification
  - 510(k): https://open.fda.gov/device/510k
  - PMA: https://open.fda.gov/device/pma
  - Registration and listing: https://open.fda.gov/device/registrationlisting
  - Recall: https://open.fda.gov/device/recall
- FDA Blog which includes background info about data sources and API limitations, which should assist in interpreting the added data:  http://blogs.fda.gov/fdavoice/index.php/2015/09/openfda-makes-medical-device-related-data-easier-to-access-and-use/

**Comment by dportnoy** [comment]
@wdanford Could you please itemize items still missing from original specifications?  Do you still need to continue with FOIA requests?

**Comment by betshsu** [comment]
Wiki has been updated with info regarding new R&L API under Solution/Long term implementation http://hhs.ddod.us/wiki/Use_Case_5:_Consolidated_registry_of_marketed_medical_devices#Long_Term_Implementation
