### ISSUE TITLE
Is there an update to - Use Case 46: Medicaid MCO Data

### ISSUE THREAD

**Issue by ghost** [demand-driven-open-data/ddod-intake#53]
We had been hoping for an updated file in February.  Anyone have an update?

Thanks,

Jeff Stewart

**Comment by dportnoy** [comment]
@BAP-Jeff  The Excel files originally requested for #46 have been made available online.  Which aspect of that request were you interested in?

cc: @DamonDavis

**Comment by ghost** [comment]
David,

I was referring to the solution section - "
- The 2014 data should be available in Feb 2016 and will be published in
  both pdf and Excel format. (info updated 14 Jan 2016)."

The data has yet to be updated.

Jeff

**Comment by dportnoy** [comment]
@BAP-Jeff, I'm reaching out to the program owners to see if they have an update.  Thanks for your patience.

**Comment by dportnoy** [comment]
@BAP-Jeff, we have an update from the program owners.  Unfortunately, the Medicaid MCO files for 2014 are still being finalized and cannot be shared yet.  They hope to have the reports finalized "within the next few weeks".  We’ll post an update as soon as the data is available.  cc:@declan

**Comment by dportnoy** [comment]
@BAP-Jeff, 2014 data is available now.  Please see: http://ddod.us/wiki/Use_Case_46#2014_Files.  There's also an update about availability of 2015.  Let me know if there are any issues.     cc:@declan

**Comment by ghost** [comment]
Great, thanks all.

Jeff
