### ISSUE TITLE
Consolidated reporting of medical device recalls

### ISSUE THREAD

**Issue by dportnoy** [demand-driven-open-data/ddod-intake#6]
Specifications: ~~https://github.com/demand-driven-open-data/ddod-intake/wiki/Use-Case-6~~
http://hhs.ddod.us/wiki/Use_Case_6

**Comment by dportnoy** [comment]
Added recommendation #3 to get involved in long term solution

**Comment by dportnoy** [comment]
@procured, please provide feedback to [solution 6](http://hhs.ddod.us/wiki/Use_Case_6).  
- Any clarifications needed?
- Issues, concerns?
- Desire to participate in feedback and validation of long term solution?

**Comment by dportnoy** [comment]
Created entry to this use case on HealthData.gov

**Comment by dportnoy** [comment]
Created starting point for machine readable data dictionary for use with [HealthData.gov](http://www.healthdata.gov/): https://github.com/demand-driven-open-data/ddod-intake/blob/master/_data/use-case-6-data-dictionary.json

**Comment by wdanford** [comment]
This accurately describes the issues we've had working with medical device recall data, and we currently make use of "Short term solution 1" to retrieve the data we need. It would be helpful for us to have more clarification around why there are two separate systems -- the RES and the Recall database, or at least what the relationships between them is. We've not been able to precisely understand why a record might appear in one and not the other, which should be considered the authority, what the historical differences are, etc.

We would certainly like to participate in feedback and validation of a long term solution.

**Comment by dportnoy** [comment]
@wdanford you should watch subscribe to notifications for this issue 

I'm checking with Data Owner on:
1. Your question.  (RES is the internal system of record.  It seems the Enforcement Reports are directly generated from RES.  I'll ask the Data Owner if the Recall database has a subset of the data.)
   
   > > "It would be helpful for us to have more clarification around why there are two separate systems -- the RES and the Recall database, or at least what the relationships between them is. "
2. Next steps on participation in long term solution

**Comment by dportnoy** [comment]
Confirmed deployment via OpenFDA scheduled for release this summer.

**Comment by dportnoy** [comment]
Update: OpenFDA has made new device data available
- Announcement: https://open.fda.gov/update/openfda-unveils-cache-of-medical-device-data/
- Location of added data on OpenFDA  (https://open.fda.gov/device/event/)
  - Device classification: https://open.fda.gov/device/classification
  - 510(k): https://open.fda.gov/device/510k
  - PMA: https://open.fda.gov/device/pma
  - Registration and listing: https://open.fda.gov/device/registrationlisting
  - Recall: https://open.fda.gov/device/recall
- FDA Blog which includes background info about data sources and API limitations, which should assist in interpreting the added data:  http://blogs.fda.gov/fdavoice/index.php/2015/09/openfda-makes-medical-device-related-data-easier-to-access-and-use/

**Comment by dportnoy** [comment]
@wdanford Could you please itemize items still missing from original specifications?

**Comment by betshsu** [comment]
Wiki has been updated with info on new Recall API and how it joins to Enforcement API under Solution/Long term solution http://hhs.ddod.us/wiki/Use_Case_6:_Consolidated_reporting_of_medical_device_recalls#Long_term_solution
